# Generated by Django 5.0.1 on 2024-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=20, unique=True, verbose_name='Звание')),
                ('rank_icon', models.ImageField(upload_to='uploaded_images', verbose_name='Иконка')),
                ('exp_start', models.IntegerField(verbose_name='Опыт')),
                ('exp_next', models.IntegerField(verbose_name='Опыт до следующего звания')),
                ('cry_bonus', models.IntegerField(verbose_name='Награда')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
    ]
