# Generated by Django 5.0.1 on 2024-07-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectionguns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
