# Generated by Django 5.0.1 on 2024-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cannon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Название')),
                ('slug_name', models.SlugField(max_length=10, unique=True, verbose_name='Слаг-название')),
                ('image', models.ImageField(upload_to='Cannons', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('Ближний бой', 'Ближний бой'), ('Малая дальность', 'Малая дальность'), ('Средняя дальность', 'Средняя дальность'), ('Большая дальность', 'Большая дальность')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пушка',
                'verbose_name_plural': 'Пушки',
            },
        ),
    ]
