# Generated by Django 5.0.1 on 2024-07-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0002_alter_cannon_slug_name'),
        ('sectionranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smoki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(upload_to='Cannons-Smoki', verbose_name='Изображение')),
                ('damage_min', models.SmallIntegerField(verbose_name='Урон (мин)')),
                ('damage_max', models.SmallIntegerField(verbose_name='Урон (макс)')),
                ('impact_force', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сила удара')),
                ('recoil_force', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отдача')),
                ('reload_speed', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Перезарядка')),
                ('rotation_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скорость поворота')),
                ('max_dmg_range', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Дальность макс поражения')),
                ('min_dmg_range', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Дальность мин поражения')),
                ('weak_dmg_percent', models.SmallIntegerField(verbose_name='Процент слабого поражения')),
                ('critical_chance', models.SmallIntegerField(verbose_name='Шанс критического урона')),
                ('critical_damage', models.SmallIntegerField(verbose_name='Критический урон')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('cannon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectioncannons.cannon', verbose_name='Пушка')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Смоки',
                'verbose_name_plural': 'Смоки',
            },
        ),
    ]
