# Generated by Django 5.0.1 on 2024-07-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0003_smoki'),
        ('sectionranks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='smoki',
            name='rotation_speed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота'),
        ),
        migrations.CreateModel(
            name='Firebird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('image', models.ImageField(upload_to='Cannons-Firebird', verbose_name='Изображение')),
                ('damage_hp_sec', models.SmallIntegerField(verbose_name='Урон (хп/сек)')),
                ('reload_speed', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Перезарядка')),
                ('attack_duration', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Длительность атаки')),
                ('rotation_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('max_dmg_range', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Дальность макс поражения')),
                ('min_dmg_range', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Дальность мин поражения')),
                ('weak_dmg_percent', models.SmallIntegerField(verbose_name='Процент слабого поражения')),
                ('burning_time', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Время горения')),
                ('cannon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectioncannons.cannon', verbose_name='Пушка')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Огнемёт',
                'verbose_name_plural': 'Огнемёт',
            },
        ),
    ]
