# Generated by Django 5.0.1 on 2024-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0004_cannon_description_alter_smoki_rotation_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebird',
            name='image',
            field=models.ImageField(null=True, upload_to='Cannons', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='smoki',
            name='image',
            field=models.ImageField(null=True, upload_to='Cannons', verbose_name='Изображение'),
        ),
    ]
