# Generated by Django 5.0.1 on 2024-07-09 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0005_alter_firebird_image_alter_smoki_image'),
        ('sectionranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Cannons', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('damage_shot', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Урон выстрела')),
                ('damage_pellet', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Урон дробинки')),
                ('impact_force_shot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сила удара выстрела')),
                ('impact_force_pellet', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Сила удара дробинки')),
                ('recoil_force', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отдача')),
                ('reload_speed', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Перезарядка')),
                ('reload_speed_clip', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Зарядка обоймы')),
                ('rotation_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('max_dmg_range', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Дальность макс поражения')),
                ('min_dmg_range', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Дальность мин поражения')),
                ('weak_dmg_percent', models.SmallIntegerField(verbose_name='Процент слабого поражения')),
                ('pellet_count', models.SmallIntegerField(verbose_name='Количество дробинок')),
                ('spread_angle_vertical', models.SmallIntegerField(verbose_name='Угол разброса (вертикальный)')),
                ('spread_angle_horizonatal', models.SmallIntegerField(verbose_name='Угол разброса (горизонтальный)')),
                ('cannon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectioncannons.cannon', verbose_name='Пушка')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Молот',
                'verbose_name_plural': 'Молот',
            },
        ),
        migrations.CreateModel(
            name='Twins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Cannons', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('damage_min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Урон (мин)')),
                ('damage_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Урон (макс)')),
                ('impact_force', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сила удара')),
                ('recoil_force', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отдача')),
                ('reload_speed', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Перезарядка')),
                ('rotation_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('projectile_speed', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Скорость снаряда')),
                ('max_dmg_range', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Дальность макс поражения')),
                ('min_dmg_range', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Дальность мин поражения')),
                ('weak_dmg_percent', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процент слабого поражения')),
                ('cannon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectioncannons.cannon', verbose_name='Пушка')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Твинс',
                'verbose_name_plural': 'Твинс',
            },
        ),
    ]
