# Generated by Django 5.0.1 on 2024-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0007_freeze_isida_railgun_ricochet_shaft_thunder_vulcan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railgun',
            name='shot_delay',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Задержка перед выстрелом'),
        ),
    ]
