# Generated by Django 5.0.1 on 2024-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0008_alter_railgun_shot_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulcan',
            name='barrel_spin_down_time',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Остановка стволов'),
        ),
        migrations.AlterField(
            model_name='vulcan',
            name='overheating_time',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Время до перегрева'),
        ),
    ]
