# Generated by Django 5.0.1 on 2024-07-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0010_alter_vulcan_min_dmg_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricochet',
            name='min_dmg_range',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Дальность мин поражения'),
        ),
        migrations.AlterField(
            model_name='thunder',
            name='min_dmg_range',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Дальность мин поражения'),
        ),
    ]
