# Generated by Django 5.0.1 on 2024-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0012_alter_ricochet_charging_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricochet',
            name='projectile_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скорость снаряда'),
        ),
    ]
