# Generated by Django 5.0.1 on 2024-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0013_alter_ricochet_projectile_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebird',
            name='burning_time',
        ),
        migrations.AddField(
            model_name='firebird',
            name='burning_damage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Урон от горения'),
            preserve_default=False,
        ),
    ]
