# Generated by Django 5.0.1 on 2024-08-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectioncannons', '0014_remove_firebird_burning_time_firebird_burning_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannon',
            name='description',
        ),
    ]
