# Generated by Django 5.0.1 on 2024-07-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectioncannons', '0014_remove_firebird_burning_time_firebird_burning_damage'),
        ('sectionhulls', '0002_dictator_hornet_hunter_mammoth_titan_vasp_viking'),
        ('sectionpaints', '0001_initial'),
        ('sectionranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmamentKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='Kits', verbose_name='Изображение')),
                ('discount', models.SmallIntegerField(verbose_name='Скидка')),
                ('cost', models.IntegerField(verbose_name='Стоимость по скидке')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('rank_end', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_rank_end', to='sectionranks.rank', verbose_name='Требуемое звание (до)')),
                ('rank_start', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_rank_start', to='sectionranks.rank', verbose_name='Требуемое звание (от)')),
            ],
            options={
                'verbose_name': 'Комплект вооружений',
                'verbose_name_plural': 'Комплекты вооружений',
            },
        ),
        migrations.CreateModel(
            name='SupplyKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='Kits', verbose_name='Изображение')),
                ('discount', models.SmallIntegerField(verbose_name='Скидка')),
                ('cost', models.IntegerField(verbose_name='Стоимость по скидке')),
                ('supply_count', models.SmallIntegerField(verbose_name='Количество припасов каждого вида')),
                ('rank_end', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_rank_end', to='sectionranks.rank', verbose_name='Требуемое звание (до)')),
                ('rank_start', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_rank_start', to='sectionranks.rank', verbose_name='Требуемое звание (от)')),
            ],
            options={
                'verbose_name': 'Комплект припасов',
                'verbose_name_plural': 'Комплекты припасов',
            },
        ),
        migrations.CreateModel(
            name='TankKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='Kits', verbose_name='Изображение')),
                ('discount', models.SmallIntegerField(verbose_name='Скидка')),
                ('cost', models.IntegerField(verbose_name='Стоимость по скидке')),
                ('cannon_modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация пушки')),
                ('hull_modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация корпуса')),
                ('cannon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectioncannons.cannon', verbose_name='Пушка')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionpaints.paint', verbose_name='Краска')),
                ('rank_end', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_rank_end', to='sectionranks.rank', verbose_name='Требуемое звание (до)')),
                ('rank_start', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_rank_start', to='sectionranks.rank', verbose_name='Требуемое звание (от)')),
            ],
            options={
                'verbose_name': 'Танковый комплект',
                'verbose_name_plural': 'Танковые комплекты',
            },
        ),
    ]
