# Generated by Django 5.0.1 on 2024-07-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
