# Generated by Django 5.0.1 on 2024-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Название')),
                ('slug_name', models.SlugField(blank=True, max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='Hulls', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('Лёгкий', 'Лёгкий'), ('Средний', 'Средний'), ('Тяжёлый', 'Тяжёлый')], max_length=7, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
    ]
