# Generated by Django 5.0.1 on 2024-07-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionhulls', '0001_initial'),
        ('sectionranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Диктатор',
                'verbose_name_plural': 'Диктатор',
            },
        ),
        migrations.CreateModel(
            name='Hornet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Хорнет',
                'verbose_name_plural': 'Хорнет',
            },
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Хантер',
                'verbose_name_plural': 'Хантер',
            },
        ),
        migrations.CreateModel(
            name='Mammoth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Мамонт',
                'verbose_name_plural': 'Мамонт',
            },
        ),
        migrations.CreateModel(
            name='Titan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Титан',
                'verbose_name_plural': 'Титан',
            },
        ),
        migrations.CreateModel(
            name='Vasp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Васп',
                'verbose_name_plural': 'Васп',
            },
        ),
        migrations.CreateModel(
            name='Viking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(choices=[('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3')], max_length=2, verbose_name='Модификация')),
                ('image', models.ImageField(null=True, upload_to='Hulls', verbose_name='Изображение')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('armor', models.SmallIntegerField(verbose_name='Броня')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная скорость')),
                ('turning_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Скорость поворота')),
                ('weight', models.SmallIntegerField(verbose_name='Масса')),
                ('power', models.SmallIntegerField(verbose_name='Мощность')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionhulls.hull', verbose_name='Корпус')),
                ('rank_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectionranks.rank', verbose_name='Требуемое звание')),
            ],
            options={
                'verbose_name': 'Викинг',
                'verbose_name_plural': 'Викинг',
            },
        ),
    ]
